idea of this form of semi-supervision might valuable in other settings too

% IDEA neighborhoods in high-dim space
% cover difficulty of finding neighborhoods in high-dim space
% (maybe plus distance measures)
% IDEA weighted reconstruction error in lle
% uniformly weighted across x_i in original paper - could it make sense to
% assign more weight to points whose neighbor hood lies more closely? So as not
% to put too much effort into points who are badly represented anyway 